module.exports = (dbinfo, Sequelize) => {
    return dbinfo.define(
        "tbl_administrateur",
        {
            id: {
                type: Sequelize.DataTypes.INTEGER,
                primaryKey: true,
                autoIncrement: true
            },
            nom: {
                type: Sequelize.DataTypes.STRING(45),
             // définir allowNull sur false ajoutera NOT NULL à la colonne, ce qui signifie qu'une 
             //erreur sera renvoyé à partir de la base de données lorsque la requête est exécutée si 
             //la colonne est null. Si vous voulez vérifier qu'une valeur n'est pas null avant d'interroger
             // la base de données, consultez la section des validations ci-dessous.
                allowNull: false
            },
            prenom: {
                type: Sequelize.DataTypes.STRING(45),
                allowNull: false
            },
            email: {
                type: Sequelize.DataTypes.STRING(255),
                allowNull: false
            },
            password: {
                 //set data type with out  max length
                 type: Sequelize.DataTypes.STRING,
                 // setting allowNull to false will add NOT NULL to the column, which means an error will be if you add info in this column
                 allowNull: false
            },
            confirm_password: {
                //donner data type with out  max length
                type: Sequelize.DataTypes.STRING,
                // setting allowNull to false will add NOT NULL to the column, which means an error will be if you add info in this column
                allowNull: false
            },
            date_naissance:{
                type: Sequelize.DataTypes.DATE,
                allowNull: false
            }
        },
        {
            /**
             * By default, Sequelize will add the attributes createdAt and updatedAt to your model so you will be able to know when the database entry went into the db and when it was updated last.
             */
            timestamps: true,
            /**
             * Sequelize allow setting underscored option for Model. When true this option will set the field option on all attributes to the underscored version of its name.
             * This also applies to foreign keys generated by associations.
             * */

            underscored: true
        }
    );
}